version: '3'

services:
  mysql:
    container_name: video_nft
    image: mysql/mysql-server:5.7
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "video_nft"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Seoul'
    ports:
      - "3305:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  volumes:
    db-data: