
server:
  port: 0

spring:
  application:
    name: user-service
  thymeleaf:
    cache: false
    prefix: file:user/src/main/resources/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/video_nft?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcom to the Simple User-service

logging:
  level:
    com.example.user: DEBUG


token:
  expiration_time: 86400000
  secret: user_token